"""
Build marker for S4-POST-RW12-PAPP-PAPER-PACKAGE-SKELETON-2026-06-23.

The package was generated by the Codex session on 2026-06-23.  The deterministic
source package is recorded in:

    FRAMEWORK/04-SOFTWARE/Metatron's Cube/FASE ESPLORATIVA/Tetra/08-mechanical-extension/paper/s4_certified_tetrahedral_hinged_mechanism/PAPER_WORKSPACE_MANIFEST.json

Regenerate by rerunning the package assembly procedure from the current project
state, using the paper_package template, A8 wrapper package, and RW12
external fabrication/reviewer package listed in that manifest.
"""

from pathlib import Path

print(Path(__file__).resolve())
print("Build marker only; see PAPER_WORKSPACE_MANIFEST.json for source lock.")
